// lib/demo-flights.js
// Hand-written demo flights for Phase 1, in the normalized FareWise shape.
// Route: Miami (MIA) -> Berlin (BER). Picked to expose honest trade-offs.
export const demoFlights = [
  {
    id: "fw_001",
    price: 420,
    currency: "USD",
    cabin: "economy",
    totalDuration: "11h 30m",
    stops: 1,
    segments: [
      { from: "MIA", to: "LIS", airline: "TAP", flightNo: "TP202", depart: "2026-07-10T18:40", arrive: "2026-07-11T07:10", duration: "7h 30m" },
      { from: "LIS", to: "BER", airline: "TAP", flightNo: "TP534", depart: "2026-07-11T09:00", arrive: "2026-07-11T13:10", duration: "3h 10m" },
    ],
    bookingType: "single-ticket",
    protected: true,
    layover: "1h 50m",
    baggage: { carryOn: true, checked: 0 },
    extraFees: { firstBag: 35, seatSelect: 12, payment: 0 },
    refundable: false,
    feesKnown: true,
    cabinOptions: [
      { cabin: "economy", price: 420 },
      { cabin: "business", price: 1310, perks: ["lie-flat", "lounge", "2 checked bags"] },
    ],
    bookVia: { name: "TAP Air Portugal", url: "https://placeholder-affiliate-link" },
  },
  {
    id: "fw_002",
    price: 360,
    currency: "USD",
    cabin: "economy",
    totalDuration: "13h 05m",
    stops: 1,
    segments: [
      { from: "MIA", to: "LGW", airline: "Norse", flightNo: "Z0701", depart: "2026-07-10T20:15", arrive: "2026-07-11T08:20", duration: "7h 05m" },
      { from: "STN", to: "BER", airline: "Ryanair", flightNo: "FR8021", depart: "2026-07-11T09:30", arrive: "2026-07-11T12:20", duration: "2h 50m" },
    ],
    bookingType: "self-transfer",
    protected: false,
    layover: "1h 10m",
    baggage: { carryOn: true, checked: 0 },
    extraFees: { firstBag: 60, seatSelect: 18, payment: 5 },
    refundable: false,
    feesKnown: true,
    cabinOptions: [{ cabin: "economy", price: 360 }],
    bookVia: { name: "Norse Atlantic", url: "https://placeholder-affiliate-link" },
  },
  {
    id: "fw_003",
    price: 690,
    currency: "USD",
    cabin: "economy",
    totalDuration: "9h 55m",
    stops: 0,
    segments: [
      { from: "MIA", to: "BER", airline: "Lufthansa", flightNo: "LH463", depart: "2026-07-10T17:25", arrive: "2026-07-11T08:20", duration: "9h 55m" },
    ],
    bookingType: "single-ticket",
    protected: true,
    layover: "",
    baggage: { carryOn: true, checked: 1 },
    extraFees: { firstBag: 0, seatSelect: 25, payment: 0 },
    refundable: false,
    feesKnown: true,
    cabinOptions: [
      { cabin: "economy", price: 690 },
      { cabin: "business", price: 2100, perks: ["lie-flat", "lounge", "priority", "2 checked bags"] },
    ],
    bookVia: { name: "Lufthansa", url: "https://placeholder-affiliate-link" },
  },
  {
    id: "fw_004",
    price: 188,
    currency: "USD",
    cabin: "economy",
    totalDuration: "16h 20m",
    stops: 1,
    segments: [
      { from: "MIA", to: "FRA", airline: "Condor", flightNo: "DE2099", depart: "2026-07-10T22:05", arrive: "2026-07-11T12:40", duration: "8h 35m" },
      { from: "FRA", to: "BER", airline: "Condor", flightNo: "DE1188", depart: "2026-07-11T18:45", arrive: "2026-07-11T19:55", duration: "1h 10m" },
    ],
    bookingType: "single-ticket",
    protected: true,
    layover: "6h 05m",
    baggage: { carryOn: true, checked: 0 },
    extraFees: { firstBag: 40, seatSelect: 10, payment: 0 },
    refundable: false,
    feesKnown: true,
    cabinOptions: [{ cabin: "economy", price: 188 }],
    bookVia: { name: "Condor", url: "https://placeholder-affiliate-link" },
  },
];
